### ISSUE TITLE
code convention discussion

### ISSUE THREAD

**Issue by shiffman** [nature-of-code/noc-book-2023#133]
Picking up on comments from @alignedleft in this thread: https://github.com/shiffman/The-Nature-of-Code-archive/issues/350 I now have the following in edition 2:

<img width="687" alt="screen shot 2016-07-11 at 2 06 50 pm" src="https://cloud.githubusercontent.com/assets/191758/16741342/e0687740-4770-11e6-94a9-3712775c2af2.png">

Any feedback @alignedleft?

**Comment by scotthmurray** [comment]
That's great! Much more clear, at least for me.

I'd suggest instead of "light grey highlighting *matches* the comments…" consider "light grey highlighting *groups* the comments…"

One more design idea (may not be feasible): Since there may be many of these interrupted snippets throughout the book, what about signifying the *start* of a code example with, say, a solid black border on the top edge of the snippet (preceding `class Walker {`, in this case).  The end of a snippet could be indicated with the same border on the bottom edge of the final excerpt.

For that matter, I'd suggest using a different color or gray for code/comment highlighting than the gray used for sidebars and other callouts.

**Comment by shiffman** [comment]
Here I am again three years later! @scotthmurray not that I expect you to follow this but you can see the latest here:

https://nature-of-code-2nd-edition.netlify.app/introduction/#i2-the-random-walker-class

@jasongao97 what do you think about the suggestion of having a horizontal gray line / bar for when a code snippet begins and closing it with another when the snippet ends (see blue lines below). My gut feeling is this is going to be complex to maintain and apply consistently (since a lot of code snippets are stand alone, but I am open to considering it.)

![image](https://user-images.githubusercontent.com/191758/218275191-551a3d2b-e772-413a-8b97-6fdd8f2af5d9.png)

**Comment by scotthmurray** [comment]
Well, color me impressed! 😁

**Comment by jasongao97** [comment]
@shiffman Technically speaking, I believe it's not hard to implement. We can just set a new callout block type and drag everything inside. e.g. the following. But I'm wondering if there are any other design choice besides a start/finish line.

- Maybe adding a vertical line with indent for the whole section.
- Or add `...` notations at the top or bottom of code blocks to infer a continuous block above/below.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/6762203/218530115-482b9390-034c-4ef2-b2e6-0314be1ebc7c.png">

**Comment by shiffman** [comment]
Yeah, I don't have a clear idea here, maybe let's put a pin in this one and revisit later. It could be really helpful but doesn't feel as high priority as other things that need to be done for the book. I'm adding @nheidelberger to this thread in case he has any thoughts!

**Comment by shiffman** [comment]
This discussion can be followed in #447!
